name: release

on:
    push:
      branches-ignore:
      - '**'
      tags:
      - 'v*'
  
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Set version
            id: version
            run: |
                REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
                VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
                echo ::set-output name=version::$VERSION
                echo ::set-output name=filename::$REPOSITORY-$VERSION
                echo "Version $VERSION"                
          - name: Checkout code
            uses: actions/checkout@v2
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
          - name: Create Zip
            uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
            with:
              type: "zip"
              directory: "./Assets/ndmf_sps"
              filename: "../../${{ steps.version.outputs.filename }}.zip" # make the zip file two directories up, since we start two directories in above
          
          - run: find "./Assets/ndmf_sps" -name \*.meta >> metaList
          - name: Create UnityPackage
            uses: pCYSl5EDgo/create-unitypackage@e28c7a4616b2754c564b0a959a03b3c89b756fdb
            with:
              package-path: "${{ steps.version.outputs.filename }}.unitypackage"
              include-files: metaList
          - name: Make Release
            uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
            with:
              tag_name: ${{ steps.version.outputs.prop }}
              files: |
                ${{ steps.version.outputs.filename }}.zip
                ${{ steps.version.outputs.filename }}.unitypackage
                ./Assets/ndmf_sps/package.json
         