name: release

on:
    push:
      branches-ignore:
      - '**'
      tags:
      - 'v*'
  
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: Set version
            id: version
            run: |
                REPOSITORY=$(echo ${{ github.repository }} | sed -e "s#.*/##")
                VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
                echo ::set-output name=version::$VERSION
                echo ::set-output name=filename::$REPOSITORY-$VERSION
                echo "Version $VERSION"                
          - name: Checkout code
            uses: actions/checkout@v2
            with:
                token: ${{ secrets.GITHUB_TOKEN }}
          - name: Create Zip
            uses: thedoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
            with:
              type: "zip"
              directory: "./ndmf_sps"
              filename: "../../${{ steps.version.outputs.filename }}.zip" # make the zip file two directories up, since we start two directories in above
          
          - name: Make Release
            uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
            with:
              tag_name: ${{ steps.version.outputs.prop }}
              files: |
                ${{ steps.version.outputs.filename }}.zip
                ./ndmf_sps/package.json
         