name: Update Repo Listing

on:
  workflow_dispatch:
  workflow_run:
    workflows: [release]
    types:
      - completed
  release:
     types: [published, created, edited, unpublished, deleted, released]

# Allow one concurrent deployment
concurrency:
  group: "Release"
  cancel-in-progress: true

jobs:
  run-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: meronmks/vpm
          event-type: Release